import { StyleSheet } from 'react-native';
import { ThemeColors } from '@/hooks/useThemeColor';

export const createLettersStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      backgroundColor: colors.headerBackground,
      paddingTop: 55,
      paddingBottom: 30,
      paddingHorizontal: 24,
      borderBottomLeftRadius: 32,
      borderBottomRightRadius: 32,
      shadowColor: colors.text,
      shadowOpacity: 0.25,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      elevation: 12,
    },
    headerTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    headerTitle: {
      color: colors.text,
      fontSize: 28,
      fontWeight: '700',
      letterSpacing: 1.5,
    },
    headerRight: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      margin: 20,
      borderRadius: 16,
      padding: 12,
      shadowColor: colors.text,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 6,
      elevation: 6,
    },
    searchIcon: { marginRight: 12 },
    searchInput: { flex: 1, color: colors.text, fontSize: 16 },
    favoritesList: { padding: 20 },
    favoriteItem: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.inputBackground,
      marginBottom: 12,
      borderRadius: 12,
      padding: 14,
      shadowColor: colors.text,
      shadowOpacity: 0.06,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 6,
      elevation: 6,
    },
    languageSelector: {
      paddingHorizontal: 15,
      marginBottom: 10,
      zIndex: 10,
      position: 'relative',
    },
    languageButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.inputBackground,
      padding: 12,
      borderRadius: 8,
      shadowColor: colors.text,
      shadowOpacity: 0.08,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 6,
      elevation: 6,
    },
    languageButtonText: {
      color: colors.text,
      fontSize: 16,
    },
    languageMenu: {
      position: 'absolute',
      top: 50,
      left: 0,
      right: 0,
      backgroundColor: colors.inputBackground,
      borderRadius: 8,
      padding: 8,
      elevation: 20,
      zIndex: 9999,
    },
    languageOption: {
      padding: 10,
      borderRadius: 6,
    },
    languageOptionActive: {
      backgroundColor: colors.border,
    },
    languageOptionText: {
      color: colors.text,
      fontSize: 16,
    },
    content: {
      flex: 1,
    },
    searchBarContainer: {
      paddingHorizontal: 135,
      marginBottom: 10,
    },
    searchBar: {
      backgroundColor: colors.inputBackground,
      borderRadius: 35,
      paddingVertical: 12,
      paddingHorizontal: 20,
      alignItems: 'center',
      shadowColor: colors.text,
      shadowOpacity: 0.05,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 4,
      elevation: 4,
    },
    searchBarText: {
      color: colors.text,
      fontSize: 30,
      fontWeight: 'bold',
    },
    mainContent: {
      flex: 1,
      flexDirection: 'row',
    },
    himnosContainer: {
      flex: 1,
      paddingLeft: 20,
    },
    himnosList: {
      paddingBottom: 20,
    },
    himnoItem: {
      backgroundColor: colors.inputBackground,
      marginBottom: 12,
      padding: 15,
      borderRadius: 12,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: colors.text,
      shadowOpacity: 0.06,
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 6,
      elevation: 6,
    },
    himnoTitle: {
      color: colors.text,
      fontSize: 16,
      flex: 1,
    },
    himnoNumber: {
      color: colors.textSecondary,
      fontWeight: 'bold',
      marginRight: 10,
    },
    lettersSidebar: {
      width: 50,
      paddingRight: 10,
      paddingLeft: 5,
    },
    letterButton: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      paddingHorizontal: 5,
      marginVertical: 2,
      borderRadius: 15,
    },
    letterButtonActive: {
      backgroundColor: colors.border,
    },
    letterText: {
      color: colors.textSecondary,
      fontSize: 14,
      fontWeight: 'bold',
    },
    letterTextActive: {
      color: colors.text,
    },
  });
